DEFAULT_PERSONAS = [
    {"TR": "Su Şartlandırma Kimyasalları ve Sistemleri Baş Mühendisi", "EN": "Head Engineer of Water Treatment Chemicals and Systems", "RU": "Главный инженер по химикатам и системам водоочистки", "AR": "كبير مهندسي المواد الكيميائية وأنظمة معالجة المياه", "FR": "Ingénieur en Chef des Produits Chimiques et Systèmes de Traitement de l'Eau", "ES": "Ingeniero Jefe de Productos Químicos y Sistemas de Tratamiento de Agua"},
    {"TR": "Endüstriyel Soğutma Sistemleri Uzmanı", "EN": "Industrial Cooling Systems Expert", "RU": "Специалист по промышленным системам охлаждения", "AR": "خبير أنظمة التبريد الصناعية", "FR": "Expert en Systèmes de Refroidissement Industriel", "ES": "Experto en Sistemas de Enfriamiento Industrial"},
    {"TR": "Ters Osmoz (RO) Membran Teknolojileri Analisti", "EN": "Reverse Osmosis (RO) Membrane Technologies Analyst", "RU": "Аналитик технологий мембран обратного осмоса", "AR": "محلل تقنيات أغشية التناضح العكسي", "FR": "Analyste des Technologies de Membranes à Osmose Inverse", "ES": "Analista de Tecnologías de Membrana de Ósmosis Inversa"},
    {"TR": "Atık Su Arıtma Tesisi Yöneticisi", "EN": "Wastewater Treatment Plant Manager", "RU": "Управляющий очистными сооружениями сточных вод", "AR": "مدير محطة معالجة مياه الصرف الصحي", "FR": "Directeur d'Usine de Traitement des Eaux Usées", "ES": "Gerente de Planta de Tratamiento de Aguas Residuales"},
    {"TR": "Kazan Suyu ve Buhar Sistemleri Danışmanı", "EN": "Boiler Water and Steam Systems Consultant", "RU": "Консультант по котловой воде и паровым системам", "AR": "مستشار مياه الغلايات وأنظمة البخار", "FR": "Consultant en Eau de Chaudière et Systèmes à Vapeur", "ES": "Consultor de Agua de Calderas y Sistemas de Vapor"}
]

LANGUAGES = {
    'TR': {
        'name': 'Turkish',
        'sys_manual': 'Manuel Giriş',
        'sys_placeholder_select': 'Seçiniz',
        'detail_info': 'Detaylı Bilgi:',
        
        # Sidebar & Tabs
        'btn_social_main': '📱 Sosyal Medya Yönetimi',
        'btn_linkedin': '🟦 LinkedIn Post',
        'btn_instagram': '🟪 Instagram Post',
        'btn_bimaks_tech': '🧪 BİMAKS TEKNİK',
        'btn_quote': '📝 Teklif Oluştur',
        'settings': '⚙️ Ayarlar',
        
        'nav_analysis': 'Sistem Analizi',
        'nav_roi': 'ROI Hesaplayıcı',
        'nav_ocr': 'Rapor Okuyucu (OCR)',
        'nav_reg': 'Global Mevzuat',
        
        # Tech Solver
        'solver_title': 'Sistem Problem Çözücü',
        'solver_ph': 'Örn: Soğutma kulesinde aşırı kışır birikimi ve korozyon problemi yaşıyoruz...',
        'lsi_info': 'Suyun pH, TDS, Sıcaklık, Kalsiyum Sertliği ve Alkalinite değerlerini girerek LSI (Langelier Saturation Index) değerini otomatik hesaplayıp AI motoruna gönderebilirsiniz.',
        'mk_water': 'Besi (Makeup) Suyu',
        'sy_water': 'Sistem Suyu',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Sıcaklık (°C)',
        'ca_req': 'Ca Sertliği (ppm)',
        'alk_req': 'M. Alkalinite (ppm)',
        'cond_opt': 'İletkenlik (µS)',
        'cl_opt': 'Klorür (ppm)',
        'so4_opt': 'Sülfat (ppm)',
        'fe_opt': 'Demir (ppm)',
        'sio2_opt': 'Silika (ppm)',
        'btn_analyze': 'Analiz Et ve Çözüm Üret',
        'lsi_result': 'LSI / RSI Değerleri Başarıyla Hesaplanıp AI Motoruna İletildi!',
        
        # ROI
        'roi_title': 'Maliyet & ROI Simülatörü',
        'roi_subtitle_inputs': 'Mevcut Durum Verileri',
        'roi_blowdown': 'Mevcut Blöf (m³/saat)',
        'roi_hours': 'Yıllık Çalışma Saati',
        'roi_coc_curr': 'Mevcut Konsantrasyon Döngüsü (CoC)',
        'roi_scale': 'Tahmini Kışır Kalınlığı (mm)',
        'roi_subtitle_costs': 'Birim Maliyetler',
        'roi_cost_water': 'Su Maliyeti (€/m³)',
        'roi_cost_energy': 'Yıllık Enerji Faturası (€)',
        'roi_cost_chem': 'Mevcut Yıllık Kimyasal Maliyeti (€)',
        'roi_subtitle_bimaks': 'BİMAKS Çözümü (Hedef)',
        'roi_coc_target': 'Hedeflenen CoC',
        'roi_dose': 'Önerilen Dozaj (ppm/m³)',
        'roi_price': 'Kimyasal Birim Fiyatı (€/kg)',
        'roi_calc_btn': 'Hesapla & Karşılaştır',
        
        # ROI Table
        'tbl_param': 'Parametre',
        'tbl_curr': 'Mevcut Durum',
        'tbl_bimaks': 'BİMAKS Çözümü',
        'tbl_save': 'Yıllık Kazanç',
        'row_water': 'Su Tüketimi (m³)',
        'row_energy': 'Enerji Maliyeti (€)',
        'row_chem': 'Kimyasal Maliyeti (€)',
        'row_total': 'TOPLAM YILLIK MALİYET',
        
        # OCR
        'ocr_title': 'Görsel Rapor Analizi',
        'ocr_desc': 'Müşteriden gelen su analiz veya otomasyon raporunun fotoğrafını yükleyin. AI sizin için okuyup yorumlayacaktır.',
        'ocr_btn': 'Analiz Et',
        
        # REG
        'reg_title': 'Regülasyon ve Mevzuat Asistanı',
        'reg_ph': 'Örn: Soğutma suyu deşarj limitleri Avrupa Birliği normlarında nedir?',
        
        # LinkedIn / Insta
        'step1_linkedin_title': '1. İçerik ve Strateji Belirleme',
        'sys_select': 'Sistem Rolü Seçin:',
        'topic': 'Konu veya Amaç:',
        'target_audience': 'Hedef Kitle:',
        'target_def': 'Sektör profesyonelleri, fabrika müdürleri, mühendisler',
        'target_plat': 'Yayın Platformu:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Önerilecek Ürün (İsteğe Bağlı):',
        'prod_link_lbl': 'Ürün Linki (İsteğe Bağlı):',
        'prompt_limit': 'Maksimum Karakter Sınırı:',
        'btn_create': 'İçerik Üret',
        'editor': 'Metin Editörü',
        'char_count': 'Karakter:',
        'visual': 'Görsel / Medya Ekle (Opsiyonel)',
        'publish': 'Yayınla',
        'publish_insta': 'Instagram\'da Yayınla',
        
        # Settings
        'settings_title': 'Genel Ayarlar',
        'set_role_mgmt': 'Personalar (Rol Yönetimi)',
        'set_add_role': 'Yeni Rol Ekle:',
        'set_del_role': 'Mevcut Rolü Sil:',
        'set_admin': 'Sistem Yöneticisi Girişi',
        'set_logo': 'Arayüz Logosu Değiştir',
        'set_logo_btn': 'Logo Yükle (Geniş / Yatay önerilir)',
        'set_theme': 'Tema Renkleri',
        'set_bg': 'Arka Plan Rengi',
        'set_txt': 'Yazı Rengi',
        'set_btn': 'Buton Rengi',
        'set_modules': 'Aktif Modüller',
        'set_save': 'Ayarları Kaydet',
        'guide_btn': 'Nasıl Kullanılır?',
        'guide_gemini_title': 'Gemini API Nedir?',
        'guide_gemini_text': 'Yapay zekanın makale yazabilmesi için Google Gemini API anahtarına ihtiyacınız vardır. aistudio.google.com adresinden ücretsiz alabilirsiniz.',
        'guide_linkedin_title': 'LinkedIn Token Nedir?',
        'guide_linkedin_text': 'Uygulama üzerinden doğrudan paylaşım yapabilmeniz için gereklidir.',
        'guide_instagram_title': 'Instagram Token Nedir?',
        'guide_instagram_text': 'Instagram Graph API üzerinden alınmalıdır.',
        'back_btn': 'Geri Dön',
        'guide_title_main': 'Önce Ayarlar menüsünden API Anahtarlarınızı girin.',
        
        # Quote
        'quote_title': 'PDF Teklif Oluşturucu',
        'q_invoice_info': 'Fatura Bilgileri:',
        'q_shipping_addr': 'Sevk Adresi:',
        'q_date': 'Tarih',
        'q_period': 'Teklif Geçerlilik Süresi:',
        'q_payment': 'Ödeme Şekli:',
        'q_bank_lbl': 'Banka ve Hesap Bilgileri:',
        'q_bank_def': 'Banka: X Bankası\nIBAN: TR00 0000 0000 0000 0000\nAlıcı: Firma Adı',
        'q_prod_name': 'Ürün Adı',
        'q_shipping_opt': 'Nakliye',
        'q_inc': 'Dahil',
        'q_exc': 'Hariç',
        'q_price': 'Birim Fiyat',
        'q_total': 'GENEL TOPLAM',
        'q_show_total': 'Alt Toplam ve Genel Toplamı Göster',
        'q_note_label': 'Teklif Altı Özel Not (Opsiyonel):',
        'q_create': 'Teklifi PDF Olarak Üret'
    },
    'EN': {
        'name': 'English',
        'sys_manual': 'Manual Entry',
        'sys_placeholder_select': 'Select',
        'detail_info': 'Detailed Information:',
        'btn_social_main': '📱 Social Media Mgmt',
        'btn_linkedin': '🟦 LinkedIn Post',
        'btn_instagram': '🟪 Instagram Post',
        'btn_bimaks_tech': '🧪 BIMAKS TECH',
        'btn_quote': '📝 Create Quote',
        'settings': '⚙️ Settings',
        'nav_analysis': 'System Analysis',
        'nav_roi': 'ROI Calculator',
        'nav_ocr': 'Report Reader (OCR)',
        'nav_reg': 'Global Regulations',
        'solver_title': 'System Problem Solver',
        'solver_ph': 'e.g., We are experiencing excessive scaling and corrosion in the cooling tower...',
        'lsi_info': 'Enter pH, TDS, Temp, Ca Hardness, and Alkalinity to calculate LSI and send it to the AI engine.',
        'mk_water': 'Makeup Water',
        'sy_water': 'System Water',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Temp (°C)',
        'ca_req': 'Ca Hardness (ppm)',
        'alk_req': 'M. Alkalinity (ppm)',
        'cond_opt': 'Conductivity (µS)',
        'cl_opt': 'Chloride (ppm)',
        'so4_opt': 'Sulfate (ppm)',
        'fe_opt': 'Iron (ppm)',
        'sio2_opt': 'Silica (ppm)',
        'btn_analyze': 'Analyze & Generate Solution',
        'lsi_result': 'LSI / RSI Values Successfully Calculated and Sent to AI!',
        'roi_title': 'Cost & ROI Simulator',
        'roi_subtitle_inputs': 'Current Status Data',
        'roi_blowdown': 'Current Blowdown (m³/h)',
        'roi_hours': 'Annual Operating Hours',
        'roi_coc_curr': 'Current Cycles of Concentration (CoC)',
        'roi_scale': 'Estimated Scale Thickness (mm)',
        'roi_subtitle_costs': 'Unit Costs',
        'roi_cost_water': 'Water Cost (€/m³)',
        'roi_cost_energy': 'Annual Energy Bill (€)',
        'roi_cost_chem': 'Current Annual Chemical Cost (€)',
        'roi_subtitle_bimaks': 'BIMAKS Solution (Target)',
        'roi_coc_target': 'Target CoC',
        'roi_dose': 'Recommended Dosage (ppm/m³)',
        'roi_price': 'Chemical Unit Price (€/kg)',
        'roi_calc_btn': 'Calculate & Compare',
        'tbl_param': 'Parameter',
        'tbl_curr': 'Current Status',
        'tbl_bimaks': 'BIMAKS Solution',
        'tbl_save': 'Annual Savings',
        'row_water': 'Water Consumption (m³)',
        'row_energy': 'Energy Cost (€)',
        'row_chem': 'Chemical Cost (€)',
        'row_total': 'TOTAL ANNUAL COST',
        'ocr_title': 'Visual Report Analysis',
        'ocr_desc': 'Upload a photo of a water analysis or automation report. AI will read and interpret it.',
        'ocr_btn': 'Analyze',
        'reg_title': 'Regulation & Compliance Assistant',
        'reg_ph': 'e.g., What are the cooling water discharge limits in EU norms?',
        'step1_linkedin_title': '1. Content and Strategy Setup',
        'sys_select': 'Select System Role:',
        'topic': 'Topic or Goal:',
        'target_audience': 'Target Audience:',
        'target_def': 'Industry professionals, plant managers, engineers',
        'target_plat': 'Publishing Platform:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Product to Recommend (Optional):',
        'prod_link_lbl': 'Product Link (Optional):',
        'prompt_limit': 'Max Character Limit:',
        'btn_create': 'Generate Content',
        'editor': 'Text Editor',
        'char_count': 'Chars:',
        'visual': 'Add Media (Optional)',
        'publish': 'Publish',
        'publish_insta': 'Publish on Instagram',
        'settings_title': 'General Settings',
        'set_role_mgmt': 'Personas (Role Mgmt)',
        'set_add_role': 'Add New Role:',
        'set_del_role': 'Delete Existing Role:',
        'set_admin': 'System Administrator Login',
        'set_logo': 'Change Interface Logo',
        'set_logo_btn': 'Upload Logo',
        'set_theme': 'Theme Colors',
        'set_bg': 'Background Color',
        'set_txt': 'Text Color',
        'set_btn': 'Button Color',
        'set_modules': 'Active Modules',
        'set_save': 'Save Settings',
        'guide_btn': 'How to Use?',
        'guide_gemini_title': 'What is Gemini API?',
        'guide_gemini_text': 'You need a Google Gemini API key. Get it free from aistudio.google.com.',
        'guide_linkedin_title': 'What is LinkedIn Token?',
        'guide_linkedin_text': 'Required for direct posting.',
        'guide_instagram_title': 'What is Instagram Token?',
        'guide_instagram_text': 'Must be obtained via Instagram Graph API.',
        'back_btn': 'Go Back',
        'guide_title_main': 'Please enter your API Keys in the Settings menu first.',
        'quote_title': 'PDF Quote Generator',
        'q_invoice_info': 'Invoice Info:',
        'q_shipping_addr': 'Shipping Address:',
        'q_date': 'Date',
        'q_period': 'Quote Validity Period:',
        'q_payment': 'Payment Method:',
        'q_bank_lbl': 'Bank Details:',
        'q_bank_def': 'Bank: X Bank\nIBAN: TR00 0000 0000 0000 0000\nBeneficiary: Company Name',
        'q_prod_name': 'Product Name',
        'q_shipping_opt': 'Shipping',
        'q_inc': 'Included',
        'q_exc': 'Excluded',
        'q_price': 'Unit Price',
        'q_total': 'GRAND TOTAL',
        'q_show_total': 'Show Subtotal and Grand Total',
        'q_note_label': 'Custom Note (Optional):',
        'q_create': 'Generate Quote PDF'
    },
    'RU': {
        'name': 'Russian',
        'sys_manual': 'Ручной ввод',
        'sys_placeholder_select': 'Выбрать',
        'detail_info': 'Подробная информация:',
        'btn_social_main': '📱 Соцсети',
        'btn_linkedin': '🟦 Пост LinkedIn',
        'btn_instagram': '🟪 Пост Instagram',
        'btn_bimaks_tech': '🧪 BIMAKS ТЕХ.',
        'btn_quote': '📝 Создать КП',
        'settings': '⚙️ Настройки',
        'nav_analysis': 'Анализ системы',
        'nav_roi': 'Калькулятор ROI',
        'nav_ocr': 'Чтение отчетов (OCR)',
        'nav_reg': 'Глобальные нормативы',
        'solver_title': 'Решение системных проблем',
        'solver_ph': 'Напр.: Чрезмерная накипь и коррозия в градирне...',
        'lsi_info': 'Введите pH, TDS, Темп., Жесткость Ca и Щелочность для расчета LSI.',
        'mk_water': 'Подпиточная вода',
        'sy_water': 'Системная вода',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Темп. (°C)',
        'ca_req': 'Жесткость Ca (ppm)',
        'alk_req': 'М. Щелочность (ppm)',
        'cond_opt': 'Проводимость (µS)',
        'cl_opt': 'Хлориды (ppm)',
        'so4_opt': 'Сульфаты (ppm)',
        'fe_opt': 'Железо (ppm)',
        'sio2_opt': 'Кремнезем (ppm)',
        'btn_analyze': 'Анализировать и Решить',
        'lsi_result': 'Значения LSI / RSI успешно рассчитаны!',
        'roi_title': 'Симулятор затрат и ROI',
        'roi_subtitle_inputs': 'Текущие данные',
        'roi_blowdown': 'Текущая продувка (м³/ч)',
        'roi_hours': 'Часы работы в год',
        'roi_coc_curr': 'Текущие циклы концентрации (CoC)',
        'roi_scale': 'Толщина накипи (мм)',
        'roi_subtitle_costs': 'Удельные затраты',
        'roi_cost_water': 'Стоимость воды (€/м³)',
        'roi_cost_energy': 'Счет за энергию (€)',
        'roi_cost_chem': 'Стоимость реагентов (€)',
        'roi_subtitle_bimaks': 'Решение BIMAKS',
        'roi_coc_target': 'Целевой CoC',
        'roi_dose': 'Рекомендуемая доза (ppm/м³)',
        'roi_price': 'Цена реагента (€/кг)',
        'roi_calc_btn': 'Рассчитать и Сравнить',
        'tbl_param': 'Параметр',
        'tbl_curr': 'Текущий статус',
        'tbl_bimaks': 'Решение BIMAKS',
        'tbl_save': 'Годовая экономия',
        'row_water': 'Потребление воды (м³)',
        'row_energy': 'Затраты на энергию (€)',
        'row_chem': 'Затраты на химию (€)',
        'row_total': 'ОБЩИЕ ЗАТРАТЫ',
        'ocr_title': 'Визуальный анализ отчета',
        'ocr_desc': 'Загрузите фото отчета об анализе воды.',
        'ocr_btn': 'Анализировать',
        'reg_title': 'Помощник по нормативам',
        'reg_ph': 'Напр.: Каковы пределы сброса в нормах ЕС?',
        'step1_linkedin_title': '1. Контент и Стратегия',
        'sys_select': 'Выберите роль системы:',
        'topic': 'Тема или цель:',
        'target_audience': 'Целевая аудитория:',
        'target_def': 'Специалисты отрасли, инженеры',
        'target_plat': 'Платформа:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Продукт (необязательно):',
        'prod_link_lbl': 'Ссылка (необязательно):',
        'prompt_limit': 'Лимит символов:',
        'btn_create': 'Создать контент',
        'editor': 'Текстовый редактор',
        'char_count': 'Символы:',
        'visual': 'Добавить медиа',
        'publish': 'Опубликовать',
        'publish_insta': 'Опубликовать в Instagram',
        'settings_title': 'Общие настройки',
        'set_role_mgmt': 'Роли системы',
        'set_add_role': 'Добавить роль:',
        'set_del_role': 'Удалить роль:',
        'set_admin': 'Логин администратора',
        'set_logo': 'Изменить логотип',
        'set_logo_btn': 'Загрузить логотип',
        'set_theme': 'Цвета темы',
        'set_bg': 'Цвет фона',
        'set_txt': 'Цвет текста',
        'set_btn': 'Цвет кнопок',
        'set_modules': 'Активные модули',
        'set_save': 'Сохранить настройки',
        'guide_btn': 'Как использовать?',
        'guide_gemini_title': 'Ключ Gemini API',
        'guide_gemini_text': 'Получите бесплатно на aistudio.google.com.',
        'guide_linkedin_title': 'Токен LinkedIn',
        'guide_linkedin_text': 'Нужен для публикаций.',
        'guide_instagram_title': 'Токен Instagram',
        'guide_instagram_text': 'Через Instagram Graph API.',
        'back_btn': 'Назад',
        'guide_title_main': 'Пожалуйста, введите ключи API в настройках.',
        'quote_title': 'Создание КП (PDF)',
        'q_invoice_info': 'Реквизиты:',
        'q_shipping_addr': 'Адрес доставки:',
        'q_date': 'Дата',
        'q_period': 'Срок действия:',
        'q_payment': 'Оплата:',
        'q_bank_lbl': 'Банковские реквизиты:',
        'q_bank_def': 'Банк: X\nIBAN: TR00\nПолучатель: Название',
        'q_prod_name': 'Наименование товара',
        'q_shipping_opt': 'Доставка',
        'q_inc': 'Вкл',
        'q_exc': 'Искл',
        'q_price': 'Цена',
        'q_total': 'ИТОГО',
        'q_show_total': 'Показывать итог',
        'q_note_label': 'Примечание:',
        'q_create': 'Создать PDF'
    },
    'AR': {
        'name': 'Arabic',
        'sys_manual': 'إدخال يدوي',
        'sys_placeholder_select': 'اختر',
        'detail_info': 'معلومات مفصلة:',
        'btn_social_main': '📱 وسائل التواصل',
        'btn_linkedin': '🟦 منشور لينكد إن',
        'btn_instagram': '🟪 منشور إنستغرام',
        'btn_bimaks_tech': '🧪 بيمكس تك',
        'btn_quote': '📝 إنشاء عرض أسعار',
        'settings': '⚙️ الإعدادات',
        'nav_analysis': 'تحليل النظام',
        'nav_roi': 'حاسبة العائد',
        'nav_ocr': 'قارئ التقارير (OCR)',
        'nav_reg': 'اللوائح العالمية',
        'solver_title': 'حل مشاكل النظام',
        'solver_ph': 'مثال: نواجه مشكلة تقشر وتآكل في برج التبريد...',
        'lsi_info': 'أدخل قيم pH و TDS لحساب LSI.',
        'mk_water': 'مياه التعويض',
        'sy_water': 'مياه النظام',
        'ph_req': 'الرقم الهيدروجيني',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'الحرارة (°C)',
        'ca_req': 'عسر الكالسيوم',
        'alk_req': 'القلوية',
        'cond_opt': 'الموصلية (µS)',
        'cl_opt': 'الكلوريد (ppm)',
        'so4_opt': 'الكبريتات (ppm)',
        'fe_opt': 'الحديد (ppm)',
        'sio2_opt': 'السيليكا (ppm)',
        'btn_analyze': 'تحليل وتوليد الحل',
        'lsi_result': 'تم حساب قيم LSI بنجاح!',
        'roi_title': 'محاكي التكلفة والعائد',
        'roi_subtitle_inputs': 'بيانات الحالة الحالية',
        'roi_blowdown': 'التفريغ الحالي',
        'roi_hours': 'ساعات العمل',
        'roi_coc_curr': 'دورات التركيز الحالية',
        'roi_scale': 'سمك القشرة',
        'roi_subtitle_costs': 'تكاليف الوحدة',
        'roi_cost_water': 'تكلفة المياه',
        'roi_cost_energy': 'فاتورة الطاقة',
        'roi_cost_chem': 'تكلفة المواد الكيميائية',
        'roi_subtitle_bimaks': 'حل بيمكس',
        'roi_coc_target': 'الهدف CoC',
        'roi_dose': 'الجرعة الموصى بها',
        'roi_price': 'سعر الوحدة',
        'roi_calc_btn': 'حساب ومقارنة',
        'tbl_param': 'المعلمة',
        'tbl_curr': 'الوضع الحالي',
        'tbl_bimaks': 'حل بيمكس',
        'tbl_save': 'التوفير السنوي',
        'row_water': 'استهلاك المياه',
        'row_energy': 'تكلفة الطاقة',
        'row_chem': 'تكلفة الكيماويات',
        'row_total': 'التكلفة الإجمالية',
        'ocr_title': 'التحليل المرئي',
        'ocr_desc': 'قم بتحميل صورة التقرير ليقرأها الذكاء الاصطناعي.',
        'ocr_btn': 'تحليل',
        'reg_title': 'مساعد اللوائح',
        'reg_ph': 'مثال: ما هي حدود التصريف في أوروبا؟',
        'step1_linkedin_title': '1. المحتوى والاستراتيجية',
        'sys_select': 'اختر دور النظام:',
        'topic': 'الموضوع:',
        'target_audience': 'الجمهور المستهدف:',
        'target_def': 'المهندسين، مديري المصانع',
        'target_plat': 'منصة النشر:',
        'plat_def': 'لينكد إن',
        'prod_ref': 'المنتج المقترح (اختياري):',
        'prod_link_lbl': 'رابط المنتج (اختياري):',
        'prompt_limit': 'الحد الأقصى للأحرف:',
        'btn_create': 'توليد المحتوى',
        'editor': 'محرر النص',
        'char_count': 'الأحرف:',
        'visual': 'إضافة وسائط',
        'publish': 'نشر',
        'publish_insta': 'نشر على إنستغرام',
        'settings_title': 'الإعدادات العامة',
        'set_role_mgmt': 'إدارة الأدوار',
        'set_add_role': 'إضافة دور:',
        'set_del_role': 'حذف دور:',
        'set_admin': 'دخول المسؤول',
        'set_logo': 'تغيير الشعار',
        'set_logo_btn': 'رفع شعار',
        'set_theme': 'ألوان السمة',
        'set_bg': 'لون الخلفية',
        'set_txt': 'لون النص',
        'set_btn': 'لون الزر',
        'set_modules': 'الوحدات النشطة',
        'set_save': 'حفظ الإعدادات',
        'guide_btn': 'كيف تستعمل؟',
        'guide_gemini_title': 'مفتاح Gemini',
        'guide_gemini_text': 'احصل عليه مجاناً من جوجل.',
        'guide_linkedin_title': 'توكن لينكد إن',
        'guide_linkedin_text': 'مطلوب للنشر.',
        'guide_instagram_title': 'توكن إنستغرام',
        'guide_instagram_text': 'عبر Graph API.',
        'back_btn': 'رجوع',
        'guide_title_main': 'أدخل مفاتيح API في الإعدادات أولاً.',
        'quote_title': 'مولد عروض الأسعار PDF',
        'q_invoice_info': 'معلومات الفاتورة:',
        'q_shipping_addr': 'عنوان الشحن:',
        'q_date': 'التاريخ',
        'q_period': 'فترة الصلاحية:',
        'q_payment': 'طريقة الدفع:',
        'q_bank_lbl': 'التفاصيل المصرفية:',
        'q_bank_def': 'البنك: X\nIBAN: TR00',
        'q_prod_name': 'اسم المنتج',
        'q_shipping_opt': 'الشحن',
        'q_inc': 'مشمول',
        'q_exc': 'غير مشمول',
        'q_price': 'سعر الوحدة',
        'q_total': 'المجموع الإجمالي',
        'q_show_total': 'عرض المجموع',
        'q_note_label': 'ملاحظة:',
        'q_create': 'إنشاء PDF'
    },
    'FR': {
        'name': 'French',
        'sys_manual': 'Saisie Manuelle',
        'sys_placeholder_select': 'Sélectionner',
        'detail_info': 'Informations Détaillées :',
        'btn_social_main': '📱 Réseaux Sociaux',
        'btn_linkedin': '🟦 Post LinkedIn',
        'btn_instagram': '🟪 Post Instagram',
        'btn_bimaks_tech': '🧪 BIMAKS TECH',
        'btn_quote': '📝 Créer un Devis',
        'settings': '⚙️ Paramètres',
        'nav_analysis': 'Analyse du Système',
        'nav_roi': 'Calculateur de ROI',
        'nav_ocr': 'Lecteur de Rapport (OCR)',
        'nav_reg': 'Réglementations Mondiales',
        'solver_title': 'Résolveur de Problèmes Système',
        'solver_ph': 'ex., Nous avons un problème d\'entartrage excessif dans la tour de refroidissement...',
        'lsi_info': 'Saisissez le pH, le TDS, la Temp, la Dureté Ca et l\'Alcalinité pour calculer le LSI.',
        'mk_water': 'Eau d\'Appoint',
        'sy_water': 'Eau du Système',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Temp (°C)',
        'ca_req': 'Dureté Ca (ppm)',
        'alk_req': 'Alcalinité M. (ppm)',
        'cond_opt': 'Conductivité (µS)',
        'cl_opt': 'Chlorure (ppm)',
        'so4_opt': 'Sulfate (ppm)',
        'fe_opt': 'Fer (ppm)',
        'sio2_opt': 'Silice (ppm)',
        'btn_analyze': 'Analyser et Générer',
        'lsi_result': 'Valeurs LSI / RSI calculées avec succès !',
        'roi_title': 'Simulateur de Coût et de ROI',
        'roi_subtitle_inputs': 'Données Actuelles',
        'roi_blowdown': 'Purge Actuelle (m³/h)',
        'roi_hours': 'Heures de Fonctionnement Annuelles',
        'roi_coc_curr': 'Cycles de Concentration Actuels (CoC)',
        'roi_scale': 'Épaisseur Estimée du Tartre (mm)',
        'roi_subtitle_costs': 'Coûts Unitaires',
        'roi_cost_water': 'Coût de l\'Eau (€/m³)',
        'roi_cost_energy': 'Facture Énergétique Annuelle (€)',
        'roi_cost_chem': 'Coût Chimique Annuel Actuel (€)',
        'roi_subtitle_bimaks': 'Solution BIMAKS (Cible)',
        'roi_coc_target': 'CoC Cible',
        'roi_dose': 'Dosage Recommandé (ppm/m³)',
        'roi_price': 'Prix Unitaire Chimique (€/kg)',
        'roi_calc_btn': 'Calculer et Comparer',
        'tbl_param': 'Paramètre',
        'tbl_curr': 'Statut Actuel',
        'tbl_bimaks': 'Solution BIMAKS',
        'tbl_save': 'Économies Annuelles',
        'row_water': 'Consommation d\'Eau (m³)',
        'row_energy': 'Coût de l\'Énergie (€)',
        'row_chem': 'Coût Chimique (€)',
        'row_total': 'COÛT TOTAL ANNUEL',
        'ocr_title': 'Analyse Visuelle de Rapport',
        'ocr_desc': 'Téléchargez une photo du rapport d\'analyse d\'eau. L\'IA le lira.',
        'ocr_btn': 'Analyser',
        'reg_title': 'Assistant Règlementaire',
        'reg_ph': 'ex. Quelles sont les limites de rejet de l\'eau selon les normes européennes ?',
        'step1_linkedin_title': '1. Contenu et Stratégie',
        'sys_select': 'Sélectionnez le rôle du système:',
        'topic': 'Sujet ou Objectif :',
        'target_audience': 'Public Cible :',
        'target_def': 'Professionnels de l\'industrie, ingénieurs',
        'target_plat': 'Plateforme :',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Produit à Recommander (Optionnel) :',
        'prod_link_lbl': 'Lien du Produit (Optionnel) :',
        'prompt_limit': 'Limite de Caractères :',
        'btn_create': 'Générer le Contenu',
        'editor': 'Éditeur de Texte',
        'char_count': 'Caractères:',
        'visual': 'Ajouter un Média',
        'publish': 'Publier',
        'publish_insta': 'Publier sur Instagram',
        'settings_title': 'Paramètres Généraux',
        'set_role_mgmt': 'Gestion des Rôles',
        'set_add_role': 'Ajouter un Nouveau Rôle:',
        'set_del_role': 'Supprimer un Rôle:',
        'set_admin': 'Connexion Administrateur',
        'set_logo': 'Changer le Logo',
        'set_logo_btn': 'Télécharger le Logo',
        'set_theme': 'Couleurs du Thème',
        'set_bg': 'Couleur de Fond',
        'set_txt': 'Couleur du Texte',
        'set_btn': 'Couleur du Bouton',
        'set_modules': 'Modules Actifs',
        'set_save': 'Enregistrer les Paramètres',
        'guide_btn': 'Comment l\'utiliser ?',
        'guide_gemini_title': 'Qu\'est-ce que l\'API Gemini ?',
        'guide_gemini_text': 'Obtenez-la gratuitement sur aistudio.google.com.',
        'guide_linkedin_title': 'Token LinkedIn',
        'guide_linkedin_text': 'Requis pour publier directement.',
        'guide_instagram_title': 'Token Instagram',
        'guide_instagram_text': 'Requis via Instagram Graph API.',
        'back_btn': 'Retour',
        'guide_title_main': 'Veuillez entrer vos clés API dans les paramètres.',
        'quote_title': 'Générateur de Devis PDF',
        'q_invoice_info': 'Informations de Facturation :',
        'q_shipping_addr': 'Adresse de Livraison :',
        'q_date': 'Date',
        'q_period': 'Durée de Validité :',
        'q_payment': 'Méthode de Paiement :',
        'q_bank_lbl': 'Détails Bancaires :',
        'q_bank_def': 'Banque : X\nIBAN : FR00\nBénéficiaire : Nom de la société',
        'q_prod_name': 'Nom du Produit',
        'q_shipping_opt': 'Expédition',
        'q_inc': 'Inclus',
        'q_exc': 'Exclu',
        'q_price': 'Prix Unitaire',
        'q_total': 'TOTAL GÉNÉRAL',
        'q_show_total': 'Afficher le Sous-total',
        'q_note_label': 'Note Personnalisée :',
        'q_create': 'Générer le PDF'
    },
    'ES': {
        'name': 'Spanish',
        'sys_manual': 'Entrada Manual',
        'sys_placeholder_select': 'Seleccionar',
        'detail_info': 'Información Detallada:',
        'btn_social_main': '📱 Redes Sociales',
        'btn_linkedin': '🟦 Post de LinkedIn',
        'btn_instagram': '🟪 Post de Instagram',
        'btn_bimaks_tech': '🧪 BIMAKS TECH',
        'btn_quote': '📝 Crear Cotización',
        'settings': '⚙️ Configuraciones',
        'nav_analysis': 'Análisis del Sistema',
        'nav_roi': 'Calculadora de ROI',
        'nav_ocr': 'Lector de Informes (OCR)',
        'nav_reg': 'Normativas Globales',
        'solver_title': 'Solucionador de Problemas',
        'solver_ph': 'ej., Tenemos un problema de exceso de incrustaciones en la torre de enfriamiento...',
        'lsi_info': 'Ingrese pH, TDS, Temp, Dureza Ca y Alcalinidad para calcular el LSI.',
        'mk_water': 'Agua de Repuesto',
        'sy_water': 'Agua del Sistema',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Temp (°C)',
        'ca_req': 'Dureza Ca (ppm)',
        'alk_req': 'Alcalinidad M. (ppm)',
        'cond_opt': 'Conductividad (µS)',
        'cl_opt': 'Cloruro (ppm)',
        'so4_opt': 'Sulfato (ppm)',
        'fe_opt': 'Hierro (ppm)',
        'sio2_opt': 'Sílice (ppm)',
        'btn_analyze': 'Analizar y Generar',
        'lsi_result': '¡Valores LSI / RSI calculados con éxito!',
        'roi_title': 'Simulador de Costos y ROI',
        'roi_subtitle_inputs': 'Datos Actuales',
        'roi_blowdown': 'Purga Actual (m³/h)',
        'roi_hours': 'Horas de Operación',
        'roi_coc_curr': 'Ciclos de Concentración (CoC)',
        'roi_scale': 'Espesor de Incrustación (mm)',
        'roi_subtitle_costs': 'Costos Unitarios',
        'roi_cost_water': 'Costo del Agua (€/m³)',
        'roi_cost_energy': 'Factura de Energía (€)',
        'roi_cost_chem': 'Costo Químico Actual (€)',
        'roi_subtitle_bimaks': 'Solución BIMAKS (Meta)',
        'roi_coc_target': 'CoC Objetivo',
        'roi_dose': 'Dosis Recomendada (ppm/m³)',
        'roi_price': 'Precio Químico (€/kg)',
        'roi_calc_btn': 'Calcular y Comparar',
        'tbl_param': 'Parámetro',
        'tbl_curr': 'Estado Actual',
        'tbl_bimaks': 'Solución BIMAKS',
        'tbl_save': 'Ahorro Anual',
        'row_water': 'Consumo de Agua (m³)',
        'row_energy': 'Costo de Energía (€)',
        'row_chem': 'Costo Químico (€)',
        'row_total': 'COSTO TOTAL',
        'ocr_title': 'Análisis Visual',
        'ocr_desc': 'Suba una foto del análisis de agua. La IA lo leerá.',
        'ocr_btn': 'Analizar',
        'reg_title': 'Asistente de Normativas',
        'reg_ph': 'ej. ¿Cuáles son los límites de descarga en las normas de la UE?',
        'step1_linkedin_title': '1. Contenido y Estrategia',
        'sys_select': 'Seleccione el Rol:',
        'topic': 'Tema u Objetivo:',
        'target_audience': 'Público Objetivo:',
        'target_def': 'Ingenieros, gerentes de planta',
        'target_plat': 'Plataforma:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Producto a Recomendar (Opcional):',
        'prod_link_lbl': 'Enlace del Producto (Opcional):',
        'prompt_limit': 'Límite de Caracteres:',
        'btn_create': 'Generar Contenido',
        'editor': 'Editor de Texto',
        'char_count': 'Caracteres:',
        'visual': 'Agregar Medio',
        'publish': 'Publicar',
        'publish_insta': 'Publicar en Instagram',
        'settings_title': 'Configuración General',
        'set_role_mgmt': 'Gestión de Roles',
        'set_add_role': 'Añadir Rol:',
        'set_del_role': 'Eliminar Rol:',
        'set_admin': 'Inicio de sesión de Admin',
        'set_logo': 'Cambiar Logo',
        'set_logo_btn': 'Subir Logo',
        'set_theme': 'Colores del Tema',
        'set_bg': 'Color de Fondo',
        'set_txt': 'Color del Texto',
        'set_btn': 'Color del Botón',
        'set_modules': 'Módulos Activos',
        'set_save': 'Guardar Configuración',
        'guide_btn': '¿Cómo utilizar?',
        'guide_gemini_title': '¿Qué es la API de Gemini?',
        'guide_gemini_text': 'Obténgalo gratis en aistudio.google.com.',
        'guide_linkedin_title': 'Token de LinkedIn',
        'guide_linkedin_text': 'Requerido para publicar directamente.',
        'guide_instagram_title': 'Token de Instagram',
        'guide_instagram_text': 'Requerido a través de Instagram Graph API.',
        'back_btn': 'Volver',
        'guide_title_main': 'Ingrese sus claves API en Configuración.',
        'quote_title': 'Generador de Cotizaciones PDF',
        'q_invoice_info': 'Datos de Facturación:',
        'q_shipping_addr': 'Dirección de Envío:',
        'q_date': 'Fecha',
        'q_period': 'Validez:',
        'q_payment': 'Método de Pago:',
        'q_bank_lbl': 'Detalles Bancarios:',
        'q_bank_def': 'Banco: X\nIBAN: ES00\nBeneficiario: Empresa',
        'q_prod_name': 'Nombre del Producto',
        'q_shipping_opt': 'Envío',
        'q_inc': 'Incluido',
        'q_exc': 'Excluido',
        'q_price': 'Precio Unitario',
        'q_total': 'GRAN TOTAL',
        'q_show_total': 'Mostrar Subtotal',
        'q_note_label': 'Nota (Opcional):',
        'q_create': 'Generar PDF'
    }
}
