DEFAULT_PERSONAS = [
    {"TR": "Su Şartlandırma Kimyasalları ve Sistemleri Baş Mühendisi", "EN": "Head Engineer of Water Treatment Chemicals and Systems", "RU": "Главный инженер по химикатам и системам водоочистки", "AR": "كبير مهندسي المواد الكيميائية وأنظمة معالجة المياه", "FR": "Ingénieur en Chef des Produits Chimiques et Systèmes de Traitement de l'Eau", "ES": "Ingeniero Jefe de Productos Químicos y Sistemas de Tratamiento de Agua"},
    {"TR": "Endüstriyel Soğutma Sistemleri Uzmanı", "EN": "Industrial Cooling Systems Expert", "RU": "Специалист по промышленным системам охлаждения", "AR": "خبير أنظمة التبريد الصناعية", "FR": "Expert en Systèmes de Refroidissement Industriel", "ES": "Experto en Sistemas de Enfriamiento Industrial"},
    {"TR": "Ters Osmoz (RO) Membran Teknolojileri Analisti", "EN": "Reverse Osmosis (RO) Membrane Technologies Analyst", "RU": "Аналитик технологий мембран обратного осмоса", "AR": "محلل تقنيات أغشية التناضح العكسي", "FR": "Analyste des Technologies de Membranes à Osmose Inverse", "ES": "Analista de Tecnologías de Membrana de Ósmosis Inversa"},
    {"TR": "Atık Su Arıtma Tesisi Yöneticisi", "EN": "Wastewater Treatment Plant Manager", "RU": "Управляющий очистными сооружениями сточных вод", "AR": "مدير محطة معالجة مياه الصرف الصحي", "FR": "Directeur d'Usine de Traitement des Eaux Usées", "ES": "Gerente de Planta de Tratamiento de Aguas Residuales"},
    {"TR": "Kazan Suyu ve Buhar Sistemleri Danışmanı", "EN": "Boiler Water and Steam Systems Consultant", "RU": "Консультант по котловой воде и паровым системам", "AR": "مستشار مياه الغلايات وأنظمة البخار", "FR": "Consultant en Eau de Chaudière et Systèmes à Vapeur", "ES": "Consultor de Agua de Calderas y Sistemas de Vapor"}
]

LANGUAGES = {
    'TR': {
        'name': 'Turkish',
        'sys_manual': 'Manuel Giriş',
        'sys_placeholder_select': 'Seçiniz',
        'detail_info': 'Detaylı Bilgi:',
        
        # Sidebar & Tabs
        'btn_social_main': '📱 Sosyal Medya Yönetimi',
        'btn_linkedin': '🟦 LinkedIn Post',
        'btn_instagram': '🟪 Instagram Post',
        'btn_bimaks_tech': '🧪 BİMAKS TEKNİK',
        'btn_quote': '📝 Teklif Oluştur',
        'settings': '⚙️ Ayarlar',
        
        'nav_analysis': 'Sistem Analizi',
        'nav_roi': 'ROI Hesaplayıcı',
        'nav_ocr': 'Rapor Okuyucu (OCR)',
        'nav_reg': 'Global Mevzuat',
        
        # Tech Solver
        'solver_title': 'Sistem Problem Çözücü',
        'solver_ph': 'Örn: Soğutma kulesinde aşırı kışır birikimi ve korozyon problemi yaşıyoruz...',
        'lsi_info': 'Suyun pH, TDS, Sıcaklık, Kalsiyum Sertliği ve Alkalinite değerlerini girerek LSI (Langelier Saturation Index) değerini otomatik hesaplayıp AI motoruna gönderebilirsiniz.',
        'mk_water': 'Besi (Makeup) Suyu',
        'sy_water': 'Sistem Suyu',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Sıcaklık (°C)',
        'ca_req': 'Ca Sertliği (ppm)',
        'alk_req': 'M. Alkalinite (ppm)',
        'cond_opt': 'İletkenlik (µS)',
        'cl_opt': 'Klorür (ppm)',
        'so4_opt': 'Sülfat (ppm)',
        'fe_opt': 'Demir (ppm)',
        'sio2_opt': 'Silika (ppm)',
        'btn_analyze': 'Analiz Et ve Çözüm Üret',
        'lsi_result': 'LSI / RSI Değerleri Başarıyla Hesaplanıp AI Motoruna İletildi!',
        
        # ROI
        'roi_title': 'Maliyet & ROI Simülatörü',
        'roi_subtitle_inputs': 'Mevcut Durum Verileri',
        'roi_blowdown': 'Mevcut Blöf (m³/saat)',
        'roi_hours': 'Yıllık Çalışma Saati',
        'roi_coc_curr': 'Mevcut Konsantrasyon Döngüsü (CoC)',
        'roi_scale': 'Tahmini Kışır Kalınlığı (mm)',
        'roi_subtitle_costs': 'Birim Maliyetler',
        'roi_cost_water': 'Su Maliyeti (€/m³)',
        'roi_cost_energy': 'Yıllık Enerji Faturası (€)',
        'roi_cost_chem': 'Mevcut Yıllık Kimyasal Maliyeti (€)',
        'roi_subtitle_bimaks': 'BİMAKS Çözümü (Hedef)',
        'roi_coc_target': 'Hedeflenen CoC',
        'roi_dose': 'Önerilen Dozaj (ppm/m³)',
        'roi_price': 'Kimyasal Birim Fiyatı (€/kg)',
        'roi_calc_btn': 'Hesapla & Karşılaştır',
        
        # ROI Table
        'tbl_param': 'Parametre',
        'tbl_curr': 'Mevcut Durum',
        'tbl_bimaks': 'BİMAKS Çözümü',
        'tbl_save': 'Yıllık Kazanç',
        'row_water': 'Su Tüketimi (m³)',
        'row_energy': 'Enerji Maliyeti (€)',
        'row_chem': 'Kimyasal Maliyeti (€)',
        'row_total': 'TOPLAM YILLIK MALİYET',
        
        # OCR
        'ocr_title': 'Görsel Rapor Analizi',
        'ocr_desc': 'Müşteriden gelen su analiz veya otomasyon raporunun fotoğrafını yükleyin. AI sizin için okuyup yorumlayacaktır.',
        'ocr_btn': 'Analiz Et',
        
        # REG
        'reg_title': 'Regülasyon ve Mevzuat Asistanı',
        'reg_ph': 'Örn: Soğutma suyu deşarj limitleri Avrupa Birliği normlarında nedir?',
        
        # LinkedIn / Insta
        'step1_linkedin_title': '1. İçerik ve Strateji Belirleme',
        'sys_select': 'Sistem Rolü Seçin:',
        'topic': 'Konu veya Amaç:',
        'target_audience': 'Hedef Kitle:',
        'target_def': 'Sektör profesyonelleri, fabrika müdürleri, mühendisler',
        'target_plat': 'Yayın Platformu:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Önerilecek Ürün (İsteğe Bağlı):',
        'prod_link_lbl': 'Ürün Linki (İsteğe Bağlı):',
        'prompt_limit': 'Maksimum Karakter Sınırı:',
        'btn_create': 'İçerik Üret',
        'editor': 'Metin Editörü',
        'char_count': 'Karakter:',
        'visual': 'Görsel / Medya Ekle (Opsiyonel)',
        'publish': 'Yayınla',
        'publish_insta': 'Instagram\'da Yayınla',
        
        # Settings
        'settings_title': 'Genel Ayarlar',
        'set_role_mgmt': 'Personalar (Rol Yönetimi)',
        'set_add_role': 'Yeni Rol Ekle:',
        'set_del_role': 'Mevcut Rolü Sil:',
        'set_admin': 'Sistem Yöneticisi Girişi',
        'set_logo': 'Arayüz Logosu Değiştir',
        'set_logo_btn': 'Logo Yükle (Geniş / Yatay önerilir)',
        'set_theme': 'Tema Renkleri',
        'set_bg': 'Arka Plan Rengi',
        'set_txt': 'Yazı Rengi',
        'set_btn': 'Buton Rengi',
        'set_modules': 'Aktif Modüller',
        'set_save': 'Ayarları Kaydet',
        'back_btn': 'Geri Dön',
        'guide_btn': 'API ve Token Bilgileri Nasıl Alınır?',
        'guide_title_main': 'Önce Ayarlar menüsünden API Anahtarlarınızı girin.',
        
        # Kapsamlı Rehber (Geri Getirilen Kısım)
        'guide_gemini_title': '1️⃣ Gemini API Anahtarı Nasıl Alınır?',
        'guide_gemini_text': 'Yapay zekanın makale yazabilmesi, formülasyon yapabilmesi ve veri analizi için Google Gemini API anahtarına ihtiyacınız vardır.\n\n1. **aistudio.google.com** adresine gidin ve Google hesabınızla giriş yapın.\n2. Sol menüden **"Get API Key"** seçeneğine tıklayın.\n3. **"Create API Key"** butonuna basarak yeni bir anahtar oluşturun.\n4. Oluşturulan anahtarı kopyalayıp yukarıdaki "Gemini API" alanına yapıştırın. *(Kullanım standart sınırlar dahilinde Google tarafından ücretsiz olarak sunulmaktadır.)*',
        'guide_linkedin_title': '2️⃣ LinkedIn Access Token Nasıl Alınır?',
        'guide_linkedin_text': 'Uygulama üzerinden doğrudan LinkedIn profilinizde veya şirket sayfanızda paylaşım yapabilmeniz için gereklidir.\n\n1. **developer.linkedin.com** adresine gidin ve "Create App" diyerek bir geliştirici uygulaması oluşturun.\n2. Uygulama ayarlarından "Share on LinkedIn" ve "Sign In with LinkedIn" yetkilerini (ürünlerini) ekleyin.\n3. **"Auth"** sekmesinden OAuth 2.0 araçlarını kullanarak kendiniz için bir **Access Token (Erişim Anahtarı)** oluşturun.\n4. Bu token\'ı kopyalayıp yukarıdaki alana yapıştırın. *(Not: LinkedIn tokenları genellikle 60 gün geçerlidir, süresi dolduğunda bu işlemi tekrarlayıp yenilemeniz gerekir.)*',
        'guide_instagram_title': '3️⃣ Instagram Token ve Account ID Nasıl Alınır?',
        'guide_instagram_text': 'Yazılım üzerinden Instagram\'da doğrudan post paylaşabilmek için Instagram Graph API gereklidir.\n\n1. Instagram hesabınızı **"İşletme"** veya **"İçerik Üretici"** hesabına çevirin ve bunu yönettiğiniz bir Facebook sayfasına bağlayın.\n2. **developers.facebook.com** adresinden bir uygulama oluşturun ve "Instagram Graph API" ürününü projenize ekleyin.\n3. API Graph Explorer üzerinden gerekli izinleri (instagram_basic, instagram_content_publish vb.) vererek bir **Access Token** oluşturun.\n4. Yine Graph Explorer üzerinden **Instagram Account ID** numaranızı sorgulayıp kopyalayın.\n5. Aldığınız bu iki bilgiyi yukarıdaki ilgili kutucuklara girerek kaydedin.',
        
        # Quote
        'quote_title': 'PDF Teklif Oluşturucu',
        'q_invoice_info': 'Fatura Bilgileri:',
        'q_shipping_addr': 'Sevk Adresi:',
        'q_date': 'Tarih',
        'q_period': 'Teklif Geçerlilik Süresi:',
        'q_payment': 'Ödeme Şekli:',
        'q_bank_lbl': 'Banka ve Hesap Bilgileri:',
        'q_bank_def': 'Banka: X Bankası\nIBAN: TR00 0000 0000 0000 0000\nAlıcı: Firma Adı',
        'q_prod_name': 'Ürün Adı',
        'q_shipping_opt': 'Nakliye',
        'q_inc': 'Dahil',
        'q_exc': 'Hariç',
        'q_price': 'Birim Fiyat',
        'q_total': 'GENEL TOPLAM',
        'q_show_total': 'Alt Toplam ve Genel Toplamı Göster',
        'q_note_label': 'Teklif Altı Özel Not (Opsiyonel):',
        'q_create': 'Teklifi PDF Olarak Üret'
    },
    'EN': {
        'name': 'English',
        'sys_manual': 'Manual Entry',
        'sys_placeholder_select': 'Select',
        'detail_info': 'Detailed Information:',
        'btn_social_main': '📱 Social Media Mgmt',
        'btn_linkedin': '🟦 LinkedIn Post',
        'btn_instagram': '🟪 Instagram Post',
        'btn_bimaks_tech': '🧪 BIMAKS TECH',
        'btn_quote': '📝 Create Quote',
        'settings': '⚙️ Settings',
        'nav_analysis': 'System Analysis',
        'nav_roi': 'ROI Calculator',
        'nav_ocr': 'Report Reader (OCR)',
        'nav_reg': 'Global Regulations',
        'solver_title': 'System Problem Solver',
        'solver_ph': 'e.g., We are experiencing excessive scaling and corrosion in the cooling tower...',
        'lsi_info': 'Enter pH, TDS, Temp, Ca Hardness, and Alkalinity to calculate LSI and send it to the AI engine.',
        'mk_water': 'Makeup Water',
        'sy_water': 'System Water',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Temp (°C)',
        'ca_req': 'Ca Hardness (ppm)',
        'alk_req': 'M. Alkalinity (ppm)',
        'cond_opt': 'Conductivity (µS)',
        'cl_opt': 'Chloride (ppm)',
        'so4_opt': 'Sulfate (ppm)',
        'fe_opt': 'Iron (ppm)',
        'sio2_opt': 'Silica (ppm)',
        'btn_analyze': 'Analyze & Generate Solution',
        'lsi_result': 'LSI / RSI Values Successfully Calculated and Sent to AI!',
        'roi_title': 'Cost & ROI Simulator',
        'roi_subtitle_inputs': 'Current Status Data',
        'roi_blowdown': 'Current Blowdown (m³/h)',
        'roi_hours': 'Annual Operating Hours',
        'roi_coc_curr': 'Current Cycles of Concentration (CoC)',
        'roi_scale': 'Estimated Scale Thickness (mm)',
        'roi_subtitle_costs': 'Unit Costs',
        'roi_cost_water': 'Water Cost (€/m³)',
        'roi_cost_energy': 'Annual Energy Bill (€)',
        'roi_cost_chem': 'Current Annual Chemical Cost (€)',
        'roi_subtitle_bimaks': 'BIMAKS Solution (Target)',
        'roi_coc_target': 'Target CoC',
        'roi_dose': 'Recommended Dosage (ppm/m³)',
        'roi_price': 'Chemical Unit Price (€/kg)',
        'roi_calc_btn': 'Calculate & Compare',
        'tbl_param': 'Parameter',
        'tbl_curr': 'Current Status',
        'tbl_bimaks': 'BIMAKS Solution',
        'tbl_save': 'Annual Savings',
        'row_water': 'Water Consumption (m³)',
        'row_energy': 'Energy Cost (€)',
        'row_chem': 'Chemical Cost (€)',
        'row_total': 'TOTAL ANNUAL COST',
        'ocr_title': 'Visual Report Analysis',
        'ocr_desc': 'Upload a photo of a water analysis or automation report. AI will read and interpret it.',
        'ocr_btn': 'Analyze',
        'reg_title': 'Regulation & Compliance Assistant',
        'reg_ph': 'e.g., What are the cooling water discharge limits in EU norms?',
        'step1_linkedin_title': '1. Content and Strategy Setup',
        'sys_select': 'Select System Role:',
        'topic': 'Topic or Goal:',
        'target_audience': 'Target Audience:',
        'target_def': 'Industry professionals, plant managers, engineers',
        'target_plat': 'Publishing Platform:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Product to Recommend (Optional):',
        'prod_link_lbl': 'Product Link (Optional):',
        'prompt_limit': 'Max Character Limit:',
        'btn_create': 'Generate Content',
        'editor': 'Text Editor',
        'char_count': 'Chars:',
        'visual': 'Add Media (Optional)',
        'publish': 'Publish',
        'publish_insta': 'Publish on Instagram',
        'settings_title': 'General Settings',
        'set_role_mgmt': 'Personas (Role Mgmt)',
        'set_add_role': 'Add New Role:',
        'set_del_role': 'Delete Existing Role:',
        'set_admin': 'System Administrator Login',
        'set_logo': 'Change Interface Logo',
        'set_logo_btn': 'Upload Logo',
        'set_theme': 'Theme Colors',
        'set_bg': 'Background Color',
        'set_txt': 'Text Color',
        'set_btn': 'Button Color',
        'set_modules': 'Active Modules',
        'set_save': 'Save Settings',
        'back_btn': 'Go Back',
        'guide_btn': 'How to get API and Token Keys?',
        'guide_title_main': 'Please enter your API Keys in the Settings menu first.',
        
        # Comprehensive Guide
        'guide_gemini_title': '1️⃣ How to get a Gemini API Key?',
        'guide_gemini_text': 'You need a Google Gemini API key for the AI to generate articles, analyze data, and formulate recipes.\n\n1. Go to **aistudio.google.com** and sign in with your Google account.\n2. Click on **"Get API Key"** from the left menu.\n3. Click the **"Create API Key"** button to generate a new key.\n4. Copy the generated key and paste it into the "Gemini API" field above. *(Usage is free within standard limits set by Google.)*',
        'guide_linkedin_title': '2️⃣ How to get a LinkedIn Access Token?',
        'guide_linkedin_text': 'Required to publish posts directly to your LinkedIn profile or company page via the app.\n\n1. Go to **developer.linkedin.com** and create a developer app by clicking "Create App".\n2. Add the "Share on LinkedIn" and "Sign In with LinkedIn" products to your app settings.\n3. Navigate to the **"Auth"** tab and use the OAuth 2.0 tools to generate an **Access Token** for your profile.\n4. Copy and paste this token into the field above. *(Note: LinkedIn tokens are usually valid for 60 days. You must repeat this process when it expires.)*',
        'guide_instagram_title': '3️⃣ How to get an Instagram Token and Account ID?',
        'guide_instagram_text': 'The Instagram Graph API is required to publish posts directly to Instagram.\n\n1. Convert your Instagram account to a **"Business"** or **"Creator"** account and link it to a Facebook page.\n2. Go to **developers.facebook.com**, create an app, and add the "Instagram Graph API" product to your project.\n3. Use the API Graph Explorer to grant necessary permissions (e.g., instagram_basic, instagram_content_publish) and generate an **Access Token**.\n4. Use the Graph Explorer again to query and copy your **Instagram Account ID**.\n5. Enter both the Token and the Account ID into the corresponding fields above and save.',
        
        'quote_title': 'PDF Quote Generator',
        'q_invoice_info': 'Invoice Info:',
        'q_shipping_addr': 'Shipping Address:',
        'q_date': 'Date',
        'q_period': 'Quote Validity Period:',
        'q_payment': 'Payment Method:',
        'q_bank_lbl': 'Bank Details:',
        'q_bank_def': 'Bank: X Bank\nIBAN: TR00 0000 0000 0000 0000\nBeneficiary: Company Name',
        'q_prod_name': 'Product Name',
        'q_shipping_opt': 'Shipping',
        'q_inc': 'Included',
        'q_exc': 'Excluded',
        'q_price': 'Unit Price',
        'q_total': 'GRAND TOTAL',
        'q_show_total': 'Show Subtotal and Grand Total',
        'q_note_label': 'Custom Note (Optional):',
        'q_create': 'Generate Quote PDF'
    },
    'RU': {
        'name': 'Russian',
        'sys_manual': 'Ручной ввод',
        'sys_placeholder_select': 'Выбрать',
        'detail_info': 'Подробная информация:',
        'btn_social_main': '📱 Соцсети',
        'btn_linkedin': '🟦 Пост LinkedIn',
        'btn_instagram': '🟪 Пост Instagram',
        'btn_bimaks_tech': '🧪 BIMAKS ТЕХ.',
        'btn_quote': '📝 Создать КП',
        'settings': '⚙️ Настройки',
        'nav_analysis': 'Анализ системы',
        'nav_roi': 'Калькулятор ROI',
        'nav_ocr': 'Чтение отчетов (OCR)',
        'nav_reg': 'Глобальные нормативы',
        'solver_title': 'Решение системных проблем',
        'solver_ph': 'Напр.: Чрезмерная накипь и коррозия в градирне...',
        'lsi_info': 'Введите pH, TDS, Темп., Жесткость Ca и Щелочность для расчета LSI.',
        'mk_water': 'Подпиточная вода',
        'sy_water': 'Системная вода',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Темп. (°C)',
        'ca_req': 'Жесткость Ca (ppm)',
        'alk_req': 'М. Щелочность (ppm)',
        'cond_opt': 'Проводимость (µS)',
        'cl_opt': 'Хлориды (ppm)',
        'so4_opt': 'Сульфаты (ppm)',
        'fe_opt': 'Железо (ppm)',
        'sio2_opt': 'Кремнезем (ppm)',
        'btn_analyze': 'Анализировать и Решить',
        'lsi_result': 'Значения LSI / RSI успешно рассчитаны!',
        'roi_title': 'Симулятор затрат и ROI',
        'roi_subtitle_inputs': 'Текущие данные',
        'roi_blowdown': 'Текущая продувка (м³/ч)',
        'roi_hours': 'Часы работы в год',
        'roi_coc_curr': 'Текущие циклы концентрации (CoC)',
        'roi_scale': 'Толщина накипи (мм)',
        'roi_subtitle_costs': 'Удельные затраты',
        'roi_cost_water': 'Стоимость воды (€/м³)',
        'roi_cost_energy': 'Счет за энергию (€)',
        'roi_cost_chem': 'Стоимость реагентов (€)',
        'roi_subtitle_bimaks': 'Решение BIMAKS',
        'roi_coc_target': 'Целевой CoC',
        'roi_dose': 'Рекомендуемая доза (ppm/м³)',
        'roi_price': 'Цена реагента (€/кг)',
        'roi_calc_btn': 'Рассчитать и Сравнить',
        'tbl_param': 'Параметр',
        'tbl_curr': 'Текущий статус',
        'tbl_bimaks': 'Решение BIMAKS',
        'tbl_save': 'Годовая экономия',
        'row_water': 'Потребление воды (м³)',
        'row_energy': 'Затраты на энергию (€)',
        'row_chem': 'Затраты на химию (€)',
        'row_total': 'ОБЩИЕ ЗАТРАТЫ',
        'ocr_title': 'Визуальный анализ отчета',
        'ocr_desc': 'Загрузите фото отчета об анализе воды.',
        'ocr_btn': 'Анализировать',
        'reg_title': 'Помощник по нормативам',
        'reg_ph': 'Напр.: Каковы пределы сброса в нормах ЕС?',
        'step1_linkedin_title': '1. Контент и Стратегия',
        'sys_select': 'Выберите роль системы:',
        'topic': 'Тема или цель:',
        'target_audience': 'Целевая аудитория:',
        'target_def': 'Специалисты отрасли, инженеры',
        'target_plat': 'Платформа:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Продукт (необязательно):',
        'prod_link_lbl': 'Ссылка (необязательно):',
        'prompt_limit': 'Лимит символов:',
        'btn_create': 'Создать контент',
        'editor': 'Текстовый редактор',
        'char_count': 'Символы:',
        'visual': 'Добавить медиа',
        'publish': 'Опубликовать',
        'publish_insta': 'Опубликовать в Instagram',
        'settings_title': 'Общие настройки',
        'set_role_mgmt': 'Роли системы',
        'set_add_role': 'Добавить роль:',
        'set_del_role': 'Удалить роль:',
        'set_admin': 'Логин администратора',
        'set_logo': 'Изменить логотип',
        'set_logo_btn': 'Загрузить логотип',
        'set_theme': 'Цвета темы',
        'set_bg': 'Цвет фона',
        'set_txt': 'Цвет текста',
        'set_btn': 'Цвет кнопок',
        'set_modules': 'Активные модули',
        'set_save': 'Сохранить настройки',
        'back_btn': 'Назад',
        'guide_btn': 'Как получить ключи API и токены?',
        'guide_title_main': 'Пожалуйста, сначала введите ключи API в настройках.',
        
        # Comprehensive Guide
        'guide_gemini_title': '1️⃣ Как получить ключ Gemini API?',
        'guide_gemini_text': 'Ключ Google Gemini API необходим ИИ для написания статей, анализа данных и формулирования рецептур.\n\n1. Перейдите на **aistudio.google.com** и войдите в свой аккаунт Google.\n2. Нажмите **"Get API Key"** в левом меню.\n3. Нажмите кнопку **"Create API Key"**, чтобы сгенерировать новый ключ.\n4. Скопируйте созданный ключ и вставьте его в поле "Gemini API" выше. *(Использование бесплатно в пределах стандартных лимитов, установленных Google.)*',
        'guide_linkedin_title': '2️⃣ Как получить токен доступа LinkedIn?',
        'guide_linkedin_text': 'Требуется для публикации постов напрямую в вашем профиле или на странице компании LinkedIn через приложение.\n\n1. Перейдите на **developer.linkedin.com** и создайте приложение разработчика, нажав "Create App".\n2. Добавьте продукты "Share on LinkedIn" и "Sign In with LinkedIn" в настройки вашего приложения.\n3. Перейдите на вкладку **"Auth"** и используйте инструменты OAuth 2.0 для генерации **Access Token (Токена доступа)** для вашего профиля.\n4. Скопируйте и вставьте этот токен в поле выше. *(Примечание: Токены LinkedIn обычно действительны 60 дней. Вам придется повторить этот процесс, когда срок его действия истечет.)*',
        'guide_instagram_title': '3️⃣ Как получить токен и ID аккаунта Instagram?',
        'guide_instagram_text': 'Instagram Graph API требуется для публикации постов напрямую в Instagram.\n\n1. Переведите свой аккаунт Instagram в статус **"Бизнес"** или **"Автор"** и свяжите его со страницей Facebook.\n2. Перейдите на **developers.facebook.com**, создайте приложение и добавьте продукт "Instagram Graph API" в свой проект.\n3. Используйте API Graph Explorer, чтобы предоставить необходимые разрешения (например, instagram_basic, instagram_content_publish) и сгенерировать **Access Token**.\n4. Снова используйте Graph Explorer, чтобы запросить и скопировать свой **Instagram Account ID**.\n5. Введите и токен, и ID аккаунта в соответствующие поля выше и сохраните.',

        'quote_title': 'Создание КП (PDF)',
        'q_invoice_info': 'Реквизиты:',
        'q_shipping_addr': 'Адрес доставки:',
        'q_date': 'Дата',
        'q_period': 'Срок действия:',
        'q_payment': 'Оплата:',
        'q_bank_lbl': 'Банковские реквизиты:',
        'q_bank_def': 'Банк: X\nIBAN: TR00\nПолучатель: Название',
        'q_prod_name': 'Наименование товара',
        'q_shipping_opt': 'Доставка',
        'q_inc': 'Вкл',
        'q_exc': 'Искл',
        'q_price': 'Цена',
        'q_total': 'ИТОГО',
        'q_show_total': 'Показывать итог',
        'q_note_label': 'Примечание:',
        'q_create': 'Создать PDF'
    },
    'AR': {
        'name': 'Arabic',
        'sys_manual': 'إدخال يدوي',
        'sys_placeholder_select': 'اختر',
        'detail_info': 'معلومات مفصلة:',
        'btn_social_main': '📱 وسائل التواصل',
        'btn_linkedin': '🟦 منشور لينكد إن',
        'btn_instagram': '🟪 منشور إنستغرام',
        'btn_bimaks_tech': '🧪 بيمكس تك',
        'btn_quote': '📝 إنشاء عرض أسعار',
        'settings': '⚙️ الإعدادات',
        'nav_analysis': 'تحليل النظام',
        'nav_roi': 'حاسبة العائد',
        'nav_ocr': 'قارئ التقارير (OCR)',
        'nav_reg': 'اللوائح العالمية',
        'solver_title': 'حل مشاكل النظام',
        'solver_ph': 'مثال: نواجه مشكلة تقشر وتآكل في برج التبريد...',
        'lsi_info': 'أدخل قيم pH و TDS لحساب LSI.',
        'mk_water': 'مياه التعويض',
        'sy_water': 'مياه النظام',
        'ph_req': 'الرقم الهيدروجيني',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'الحرارة (°C)',
        'ca_req': 'عسر الكالسيوم',
        'alk_req': 'القلوية',
        'cond_opt': 'الموصلية (µS)',
        'cl_opt': 'الكلوريد (ppm)',
        'so4_opt': 'الكبريتات (ppm)',
        'fe_opt': 'الحديد (ppm)',
        'sio2_opt': 'السيليكا (ppm)',
        'btn_analyze': 'تحليل وتوليد الحل',
        'lsi_result': 'تم حساب قيم LSI بنجاح!',
        'roi_title': 'محاكي التكلفة والعائد',
        'roi_subtitle_inputs': 'بيانات الحالة الحالية',
        'roi_blowdown': 'التفريغ الحالي',
        'roi_hours': 'ساعات العمل',
        'roi_coc_curr': 'دورات التركيز الحالية',
        'roi_scale': 'سمك القشرة',
        'roi_subtitle_costs': 'تكاليف الوحدة',
        'roi_cost_water': 'تكلفة المياه',
        'roi_cost_energy': 'فاتورة الطاقة',
        'roi_cost_chem': 'تكلفة المواد الكيميائية',
        'roi_subtitle_bimaks': 'حل بيمكس',
        'roi_coc_target': 'الهدف CoC',
        'roi_dose': 'الجرعة الموصى بها',
        'roi_price': 'سعر الوحدة',
        'roi_calc_btn': 'حساب ومقارنة',
        'tbl_param': 'المعلمة',
        'tbl_curr': 'الوضع الحالي',
        'tbl_bimaks': 'حل بيمكس',
        'tbl_save': 'التوفير السنوي',
        'row_water': 'استهلاك المياه',
        'row_energy': 'تكلفة الطاقة',
        'row_chem': 'تكلفة الكيماويات',
        'row_total': 'التكلفة الإجمالية',
        'ocr_title': 'التحليل المرئي',
        'ocr_desc': 'قم بتحميل صورة التقرير ليقرأها الذكاء الاصطناعي.',
        'ocr_btn': 'تحليل',
        'reg_title': 'مساعد اللوائح',
        'reg_ph': 'مثال: ما هي حدود التصريف في أوروبا؟',
        'step1_linkedin_title': '1. المحتوى والاستراتيجية',
        'sys_select': 'اختر دور النظام:',
        'topic': 'الموضوع:',
        'target_audience': 'الجمهور المستهدف:',
        'target_def': 'المهندسين، مديري المصانع',
        'target_plat': 'منصة النشر:',
        'plat_def': 'لينكد إن',
        'prod_ref': 'المنتج المقترح (اختياري):',
        'prod_link_lbl': 'رابط المنتج (اختياري):',
        'prompt_limit': 'الحد الأقصى للأحرف:',
        'btn_create': 'توليد المحتوى',
        'editor': 'محرر النص',
        'char_count': 'الأحرف:',
        'visual': 'إضافة وسائط',
        'publish': 'نشر',
        'publish_insta': 'نشر على إنستغرام',
        'settings_title': 'الإعدادات العامة',
        'set_role_mgmt': 'إدارة الأدوار',
        'set_add_role': 'إضافة دور:',
        'set_del_role': 'حذف دور:',
        'set_admin': 'دخول المسؤول',
        'set_logo': 'تغيير الشعار',
        'set_logo_btn': 'رفع شعار',
        'set_theme': 'ألوان السمة',
        'set_bg': 'لون الخلفية',
        'set_txt': 'لون النص',
        'set_btn': 'لون الزر',
        'set_modules': 'الوحدات النشطة',
        'set_save': 'حفظ الإعدادات',
        'back_btn': 'رجوع',
        'guide_btn': 'كيفية الحصول على مفاتيح API؟',
        'guide_title_main': 'يرجى إدخال مفاتيح API الخاصة بك في قائمة الإعدادات أولاً.',
        
        # Comprehensive Guide
        'guide_gemini_title': '1️⃣ كيفية الحصول على مفتاح Gemini API؟',
        'guide_gemini_text': 'تحتاج إلى مفتاح Google Gemini API لكي يتمكن الذكاء الاصطناعي من كتابة المقالات وتحليل البيانات وتكوين الوصفات.\n\n1. انتقل إلى **aistudio.google.com** وسجل الدخول بحساب Google الخاص بك.\n2. انقر على **"Get API Key"** من القائمة اليسرى.\n3. انقر على زر **"Create API Key"** لإنشاء مفتاح جديد.\n4. انسخ المفتاح الذي تم إنشاؤه والصقه في حقل "Gemini API" أعلاه. *(الاستخدام مجاني ضمن الحدود القياسية التي تحددها Google.)*',
        'guide_linkedin_title': '2️⃣ كيفية الحصول على رمز وصول LinkedIn؟',
        'guide_linkedin_text': 'مطلوب لنشر المنشورات مباشرة على ملفك الشخصي في LinkedIn أو صفحة شركتك عبر التطبيق.\n\n1. انتقل إلى **developer.linkedin.com** وأنشئ تطبيق مطور بالنقر على "Create App".\n2. أضف منتجات "Share on LinkedIn" و "Sign In with LinkedIn" إلى إعدادات تطبيقك.\n3. انتقل إلى علامة التبويب **"Auth"** واستخدم أدوات OAuth 2.0 لإنشاء **Access Token (رمز وصول)** لملفك الشخصي.\n4. انسخ والصق هذا الرمز في الحقل أعلاه. *(ملاحظة: رموز LinkedIn صالحة عادة لمدة 60 يومًا. يجب عليك تكرار هذه العملية عند انتهاء صلاحيتها.)*',
        'guide_instagram_title': '3️⃣ كيفية الحصول على رمز Instagram ومعرف الحساب؟',
        'guide_instagram_text': 'مطلوب Instagram Graph API لنشر المنشورات مباشرة على Instagram.\n\n1. حول حساب Instagram الخاص بك إلى حساب **"أعمال"** أو **"منشئ محتوى"** واربطه بصفحة Facebook.\n2. انتقل إلى **developers.facebook.com**، وقم بإنشاء تطبيق، وأضف منتج "Instagram Graph API" إلى مشروعك.\n3. استخدم API Graph Explorer لمنح الأذونات اللازمة (مثل instagram_basic و instagram_content_publish) وإنشاء **Access Token**.\n4. استخدم Graph Explorer مرة أخرى للاستعلام عن **Instagram Account ID** الخاص بك ونسخه.\n5. أدخل كلاً من الرمز ومعرف الحساب في الحقول المقابلة أعلاه واحفظ.',

        'quote_title': 'مولد عروض الأسعار PDF',
        'q_invoice_info': 'معلومات الفاتورة:',
        'q_shipping_addr': 'عنوان الشحن:',
        'q_date': 'التاريخ',
        'q_period': 'فترة الصلاحية:',
        'q_payment': 'طريقة الدفع:',
        'q_bank_lbl': 'التفاصيل المصرفية:',
        'q_bank_def': 'البنك: X\nIBAN: TR00',
        'q_prod_name': 'اسم المنتج',
        'q_shipping_opt': 'الشحن',
        'q_inc': 'مشمول',
        'q_exc': 'غير مشمول',
        'q_price': 'سعر الوحدة',
        'q_total': 'المجموع الإجمالي',
        'q_show_total': 'عرض المجموع',
        'q_note_label': 'ملاحظة:',
        'q_create': 'إنشاء PDF'
    },
    'FR': {
        'name': 'French',
        'sys_manual': 'Saisie Manuelle',
        'sys_placeholder_select': 'Sélectionner',
        'detail_info': 'Informations Détaillées :',
        'btn_social_main': '📱 Réseaux Sociaux',
        'btn_linkedin': '🟦 Post LinkedIn',
        'btn_instagram': '🟪 Post Instagram',
        'btn_bimaks_tech': '🧪 BIMAKS TECH',
        'btn_quote': '📝 Créer un Devis',
        'settings': '⚙️ Paramètres',
        'nav_analysis': 'Analyse du Système',
        'nav_roi': 'Calculateur de ROI',
        'nav_ocr': 'Lecteur de Rapport (OCR)',
        'nav_reg': 'Réglementations Mondiales',
        'solver_title': 'Résolveur de Problèmes Système',
        'solver_ph': 'ex., Nous avons un problème d\'entartrage excessif dans la tour de refroidissement...',
        'lsi_info': 'Saisissez le pH, le TDS, la Temp, la Dureté Ca et l\'Alcalinité pour calculer le LSI.',
        'mk_water': 'Eau d\'Appoint',
        'sy_water': 'Eau du Système',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Temp (°C)',
        'ca_req': 'Dureté Ca (ppm)',
        'alk_req': 'Alcalinité M. (ppm)',
        'cond_opt': 'Conductivité (µS)',
        'cl_opt': 'Chlorure (ppm)',
        'so4_opt': 'Sulfate (ppm)',
        'fe_opt': 'Fer (ppm)',
        'sio2_opt': 'Silice (ppm)',
        'btn_analyze': 'Analyser et Générer',
        'lsi_result': 'Valeurs LSI / RSI calculées avec succès !',
        'roi_title': 'Simulateur de Coût et de ROI',
        'roi_subtitle_inputs': 'Données Actuelles',
        'roi_blowdown': 'Purge Actuelle (m³/h)',
        'roi_hours': 'Heures de Fonctionnement Annuelles',
        'roi_coc_curr': 'Cycles de Concentration Actuels (CoC)',
        'roi_scale': 'Épaisseur Estimée du Tartre (mm)',
        'roi_subtitle_costs': 'Coûts Unitaires',
        'roi_cost_water': 'Coût de l\'Eau (€/m³)',
        'roi_cost_energy': 'Facture Énergétique Annuelle (€)',
        'roi_cost_chem': 'Coût Chimique Annuel Actuel (€)',
        'roi_subtitle_bimaks': 'Solution BIMAKS (Cible)',
        'roi_coc_target': 'CoC Cible',
        'roi_dose': 'Dosage Recommandé (ppm/m³)',
        'roi_price': 'Prix Unitaire Chimique (€/kg)',
        'roi_calc_btn': 'Calculer et Comparer',
        'tbl_param': 'Paramètre',
        'tbl_curr': 'Statut Actuel',
        'tbl_bimaks': 'Solution BIMAKS',
        'tbl_save': 'Économies Annuelles',
        'row_water': 'Consommation d\'Eau (m³)',
        'row_energy': 'Coût de l\'Énergie (€)',
        'row_chem': 'Coût Chimique (€)',
        'row_total': 'COÛT TOTAL ANNUEL',
        'ocr_title': 'Analyse Visuelle de Rapport',
        'ocr_desc': 'Téléchargez une photo du rapport d\'analyse d\'eau. L\'IA le lira.',
        'ocr_btn': 'Analyser',
        'reg_title': 'Assistant Règlementaire',
        'reg_ph': 'ex. Quelles sont les limites de rejet de l\'eau selon les normes européennes ?',
        'step1_linkedin_title': '1. Contenu et Stratégie',
        'sys_select': 'Sélectionnez le rôle du système:',
        'topic': 'Sujet ou Objectif :',
        'target_audience': 'Public Cible :',
        'target_def': 'Professionnels de l\'industrie, ingénieurs',
        'target_plat': 'Plateforme :',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Produit à Recommander (Optionnel) :',
        'prod_link_lbl': 'Lien du Produit (Optionnel) :',
        'prompt_limit': 'Limite de Caractères :',
        'btn_create': 'Générer le Contenu',
        'editor': 'Éditeur de Texte',
        'char_count': 'Caractères:',
        'visual': 'Ajouter un Média',
        'publish': 'Publier',
        'publish_insta': 'Publier sur Instagram',
        'settings_title': 'Paramètres Généraux',
        'set_role_mgmt': 'Gestion des Rôles',
        'set_add_role': 'Ajouter un Nouveau Rôle:',
        'set_del_role': 'Supprimer un Rôle:',
        'set_admin': 'Connexion Administrateur',
        'set_logo': 'Changer le Logo',
        'set_logo_btn': 'Télécharger le Logo',
        'set_theme': 'Couleurs du Thème',
        'set_bg': 'Couleur de Fond',
        'set_txt': 'Couleur du Texte',
        'set_btn': 'Couleur du Bouton',
        'set_modules': 'Modules Actifs',
        'set_save': 'Enregistrer les Paramètres',
        'back_btn': 'Retour',
        'guide_btn': 'Comment obtenir les clés API et les Tokens ?',
        'guide_title_main': 'Veuillez d\'abord entrer vos clés API dans le menu Paramètres.',
        
        # Comprehensive Guide
        'guide_gemini_title': '1️⃣ Comment obtenir une clé API Gemini ?',
        'guide_gemini_text': 'Vous avez besoin d\'une clé API Google Gemini pour que l\'IA génère des articles, analyse des données et formule des recettes.\n\n1. Allez sur **aistudio.google.com** et connectez-vous avec votre compte Google.\n2. Cliquez sur **"Get API Key"** dans le menu de gauche.\n3. Cliquez sur le bouton **"Create API Key"** pour générer une nouvelle clé.\n4. Copiez la clé générée et collez-la dans le champ "Gemini API" ci-dessus. *(L\'utilisation est gratuite dans les limites standards fixées par Google.)*',
        'guide_linkedin_title': '2️⃣ Comment obtenir un Token d\'accès LinkedIn ?',
        'guide_linkedin_text': 'Requis pour publier des articles directement sur votre profil LinkedIn ou votre page d\'entreprise via l\'application.\n\n1. Allez sur **developer.linkedin.com** et créez une application de développeur en cliquant sur "Create App".\n2. Ajoutez les produits "Share on LinkedIn" et "Sign In with LinkedIn" aux paramètres de votre application.\n3. Accédez à l\'onglet **"Auth"** et utilisez les outils OAuth 2.0 pour générer un **Access Token (Token d\'accès)** pour votre profil.\n4. Copiez et collez ce token dans le champ ci-dessus. *(Note : Les tokens LinkedIn sont généralement valables 60 jours. Vous devez répéter ce processus lorsqu\'il expire.)*',
        'guide_instagram_title': '3️⃣ Comment obtenir un Token et un ID de compte Instagram ?',
        'guide_instagram_text': 'L\'API Instagram Graph est requise pour publier des posts directement sur Instagram.\n\n1. Convertissez votre compte Instagram en compte **"Professionnel"** ou **"Créateur"** et liez-le à une page Facebook.\n2. Allez sur **developers.facebook.com**, créez une application et ajoutez le produit "Instagram Graph API" à votre projet.\n3. Utilisez l\'API Graph Explorer pour accorder les autorisations nécessaires (par exemple, instagram_basic, instagram_content_publish) et générer un **Access Token**.\n4. Utilisez à nouveau l\'explorateur Graph pour interroger et copier votre **Instagram Account ID (ID de compte Instagram)**.\n5. Saisissez à la fois le Token et l\'ID de compte dans les champs correspondants ci-dessus et enregistrez.',

        'quote_title': 'Générateur de Devis PDF',
        'q_invoice_info': 'Informations de Facturation :',
        'q_shipping_addr': 'Adresse de Livraison :',
        'q_date': 'Date',
        'q_period': 'Durée de Validité :',
        'q_payment': 'Méthode de Paiement :',
        'q_bank_lbl': 'Détails Bancaires :',
        'q_bank_def': 'Banque : X\nIBAN : FR00\nBénéficiaire : Nom de la société',
        'q_prod_name': 'Nom du Produit',
        'q_shipping_opt': 'Expédition',
        'q_inc': 'Inclus',
        'q_exc': 'Exclu',
        'q_price': 'Prix Unitaire',
        'q_total': 'TOTAL GÉNÉRAL',
        'q_show_total': 'Afficher le Sous-total',
        'q_note_label': 'Note Personnalisée :',
        'q_create': 'Générer le PDF'
    },
    'ES': {
        'name': 'Spanish',
        'sys_manual': 'Entrada Manual',
        'sys_placeholder_select': 'Seleccionar',
        'detail_info': 'Información Detallada:',
        'btn_social_main': '📱 Redes Sociales',
        'btn_linkedin': '🟦 Post de LinkedIn',
        'btn_instagram': '🟪 Post de Instagram',
        'btn_bimaks_tech': '🧪 BIMAKS TECH',
        'btn_quote': '📝 Crear Cotización',
        'settings': '⚙️ Configuraciones',
        'nav_analysis': 'Análisis del Sistema',
        'nav_roi': 'Calculadora de ROI',
        'nav_ocr': 'Lector de Informes (OCR)',
        'nav_reg': 'Normativas Globales',
        'solver_title': 'Solucionador de Problemas',
        'solver_ph': 'ej., Tenemos un problema de exceso de incrustaciones en la torre de enfriamiento...',
        'lsi_info': 'Ingrese pH, TDS, Temp, Dureza Ca y Alcalinidad para calcular el LSI.',
        'mk_water': 'Agua de Repuesto',
        'sy_water': 'Agua del Sistema',
        'ph_req': 'pH',
        'tds_req': 'TDS (ppm)',
        'temp_req': 'Temp (°C)',
        'ca_req': 'Dureza Ca (ppm)',
        'alk_req': 'Alcalinidad M. (ppm)',
        'cond_opt': 'Conductividad (µS)',
        'cl_opt': 'Cloruro (ppm)',
        'so4_opt': 'Sulfato (ppm)',
        'fe_opt': 'Hierro (ppm)',
        'sio2_opt': 'Sílice (ppm)',
        'btn_analyze': 'Analizar y Generar',
        'lsi_result': '¡Valores LSI / RSI calculados con éxito!',
        'roi_title': 'Simulador de Costos y ROI',
        'roi_subtitle_inputs': 'Datos Actuales',
        'roi_blowdown': 'Purga Actual (m³/h)',
        'roi_hours': 'Horas de Operación',
        'roi_coc_curr': 'Ciclos de Concentración (CoC)',
        'roi_scale': 'Espesor de Incrustación (mm)',
        'roi_subtitle_costs': 'Costos Unitarios',
        'roi_cost_water': 'Costo del Agua (€/m³)',
        'roi_cost_energy': 'Factura de Energía (€)',
        'roi_cost_chem': 'Costo Químico Actual (€)',
        'roi_subtitle_bimaks': 'Solución BIMAKS (Meta)',
        'roi_coc_target': 'CoC Objetivo',
        'roi_dose': 'Dosis Recomendada (ppm/m³)',
        'roi_price': 'Precio Químico (€/kg)',
        'roi_calc_btn': 'Calcular y Comparar',
        'tbl_param': 'Parámetro',
        'tbl_curr': 'Estado Actual',
        'tbl_bimaks': 'Solución BIMAKS',
        'tbl_save': 'Ahorro Anual',
        'row_water': 'Consumo de Agua (m³)',
        'row_energy': 'Costo de Energía (€)',
        'row_chem': 'Costo Químico (€)',
        'row_total': 'COSTO TOTAL',
        'ocr_title': 'Análisis Visual',
        'ocr_desc': 'Suba una foto del análisis de agua. La IA lo leerá.',
        'ocr_btn': 'Analizar',
        'reg_title': 'Asistente de Normativas',
        'reg_ph': 'ej. ¿Cuáles son los límites de descarga en las normas de la UE?',
        'step1_linkedin_title': '1. Contenido y Estrategia',
        'sys_select': 'Seleccione el Rol:',
        'topic': 'Tema u Objetivo:',
        'target_audience': 'Público Objetivo:',
        'target_def': 'Ingenieros, gerentes de planta',
        'target_plat': 'Plataforma:',
        'plat_def': 'LinkedIn',
        'prod_ref': 'Producto a Recomendar (Opcional):',
        'prod_link_lbl': 'Enlace del Producto (Opcional):',
        'prompt_limit': 'Límite de Caracteres:',
        'btn_create': 'Generar Contenido',
        'editor': 'Editor de Texto',
        'char_count': 'Caracteres:',
        'visual': 'Agregar Medio',
        'publish': 'Publicar',
        'publish_insta': 'Publicar en Instagram',
        'settings_title': 'Configuración General',
        'set_role_mgmt': 'Gestión de Roles',
        'set_add_role': 'Añadir Rol:',
        'set_del_role': 'Eliminar Rol:',
        'set_admin': 'Inicio de sesión de Admin',
        'set_logo': 'Cambiar Logo',
        'set_logo_btn': 'Subir Logo',
        'set_theme': 'Colores del Tema',
        'set_bg': 'Color de Fondo',
        'set_txt': 'Color del Texto',
        'set_btn': 'Color del Botón',
        'set_modules': 'Módulos Activos',
        'set_save': 'Guardar Configuración',
        'back_btn': 'Volver',
        'guide_btn': '¿Cómo obtener claves API y Tokens?',
        'guide_title_main': 'Ingrese sus claves API en Configuración.',
        
        # Comprehensive Guide
        'guide_gemini_title': '1️⃣ ¿Cómo obtener una clave API de Gemini?',
        'guide_gemini_text': 'Necesita una clave API de Google Gemini para que la IA genere artículos, analice datos y formule recetas.\n\n1. Vaya a **aistudio.google.com** e inicie sesión con su cuenta de Google.\n2. Haga clic en **"Get API Key"** en el menú de la izquierda.\n3. Haga clic en el botón **"Create API Key"** para generar una nueva clave.\n4. Copie la clave generada y péguela en el campo "Gemini API" de arriba. *(El uso es gratuito dentro de los límites estándar establecidos por Google.)*',
        'guide_linkedin_title': '2️⃣ ¿Cómo obtener un token de acceso a LinkedIn?',
        'guide_linkedin_text': 'Requerido para publicar entradas directamente en su perfil de LinkedIn o página de empresa a través de la aplicación.\n\n1. Vaya a **developer.linkedin.com** y cree una aplicación de desarrollador haciendo clic en "Create App".\n2. Agregue los productos "Share on LinkedIn" y "Sign In with LinkedIn" a la configuración de su aplicación.\n3. Navegue a la pestaña **"Auth"** y use las herramientas de OAuth 2.0 para generar un **Access Token (Token de acceso)** para su perfil.\n4. Copie y pegue este token en el campo de arriba. *(Nota: Los tokens de LinkedIn generalmente son válidos por 60 días. Debe repetir este proceso cuando caduque.)*',
        'guide_instagram_title': '3️⃣ ¿Cómo obtener un Token y un ID de cuenta de Instagram?',
        'guide_instagram_text': 'Se requiere la API Graph de Instagram para publicar entradas directamente en Instagram.\n\n1. Convierta su cuenta de Instagram en una cuenta de **"Empresa"** o **"Creador"** y vincúlela a una página de Facebook.\n2. Vaya a **developers.facebook.com**, cree una aplicación y agregue el producto "Instagram Graph API" a su proyecto.\n3. Use el API Graph Explorer para otorgar los permisos necesarios (por ejemplo, instagram_basic, instagram_content_publish) y generar un **Access Token**.\n4. Use el Graph Explorer nuevamente para consultar y copiar su **Instagram Account ID (ID de cuenta de Instagram)**.\n5. Ingrese tanto el Token como el ID de cuenta en los campos correspondientes de arriba y guarde.',

        'quote_title': 'Generador de Cotizaciones PDF',
        'q_invoice_info': 'Datos de Facturación:',
        'q_shipping_addr': 'Dirección de Envío:',
        'q_date': 'Fecha',
        'q_period': 'Validez:',
        'q_payment': 'Método de Pago:',
        'q_bank_lbl': 'Detalles Bancarios:',
        'q_bank_def': 'Banco: X\nIBAN: ES00\nBeneficiario: Empresa',
        'q_prod_name': 'Nombre del Producto',
        'q_shipping_opt': 'Envío',
        'q_inc': 'Incluido',
        'q_exc': 'Excluido',
        'q_price': 'Precio Unitario',
        'q_total': 'GRAN TOTAL',
        'q_show_total': 'Mostrar Subtotal',
        'q_note_label': 'Nota (Opcional):',
        'q_create': 'Generar PDF'
    }
}
